#!/usr/bin/env python

import sys
import os


def usage():
    print """Usage: dupdir <dir1> <dir2>

Prints all those directories from <dir1> that are also present in <dir2>. That
is, a directory of the same name is present in <dir2>.
"""


def _is_directory(d):
    return os.path.exists(d) and os.path.isdir(d)


def subdir_list(d):
    entries = os.listdir(d)
    entries.sort()
    return entries


def subdir_dict(d):
    entries = subdir_list(d)
    result = {}
    for e in entries:
        result[e] = True
    return result


def main():

    if len(sys.argv) != 3:
        usage()
        sys.exit(1)

    dir1 = sys.argv[1]
    dir2 = sys.argv[2]

    if not _is_directory(dir1):
        print dir1 + " is not a valid directory, stopping."
        sys.exit(1)

    if not _is_directory(dir2):
        print dir2 + " is not a valid directory, stopping."
        sys.exit(1)

    subdirs1 = subdir_list(dir1)
    subdirs2 = subdir_dict(dir2)

    for d in subdirs1:
        if d in subdirs2:
            print d


if __name__ == "__main__":
    main()
